/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apollo_cyber_RecordWriter */

#ifndef _Included_com_apollo_cyber_RecordWriter
#define _Included_com_apollo_cyber_RecordWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    createWriter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apollo_cyber_RecordWriter_createWriter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    destroyWriter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apollo_cyber_RecordWriter_destroyWriter
  (JNIEnv *, jobject);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    writeChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apollo_cyber_RecordWriter_writeChannel
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    writeMessage
 * Signature: (Ljava/lang/String;[BJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apollo_cyber_RecordWriter_writeMessage
  (JNIEnv *, jobject, jstring, jbyteArray, jlong, jstring);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    setSizeOfFileSegmentation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apollo_cyber_RecordWriter_setSizeOfFileSegmentation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    setIntervalOfFileSegmentation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apollo_cyber_RecordWriter_setIntervalOfFileSegmentation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    getMessageNumber
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_apollo_cyber_RecordWriter_getMessageNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    getMessageType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apollo_cyber_RecordWriter_getMessageType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordWriter
 * Method:    getProtoDesc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apollo_cyber_RecordWriter_getProtoDesc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
