/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apollo_cyber_RecordReader */

#ifndef _Included_com_apollo_cyber_RecordReader
#define _Included_com_apollo_cyber_RecordReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    createReader
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apollo_cyber_RecordReader_createReader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    destroyReader
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apollo_cyber_RecordReader_destroyReader
  (JNIEnv *, jobject);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    readMessage
 * Signature: (JJ)Lcom/apollo/cyber/RecordBagMessage;
 */
JNIEXPORT jobject JNICALL Java_com_apollo_cyber_RecordReader_readMessage
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    getMessageNumber
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apollo_cyber_RecordReader_getMessageNumber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    getMessageType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apollo_cyber_RecordReader_getMessageType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    getProtoDesc
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_apollo_cyber_RecordReader_getProtoDesc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    getHeaderString
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_apollo_cyber_RecordReader_getHeaderString
  (JNIEnv *, jobject);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    getHeaderJson
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apollo_cyber_RecordReader_getHeaderJson
  (JNIEnv *, jobject);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apollo_cyber_RecordReader_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_apollo_cyber_RecordReader
 * Method:    getChannelList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_apollo_cyber_RecordReader_getChannelList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
